"use client";
import { ArrowRight, Download, Plus, Server, ShieldCheck } from "lucide-react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "./ui/card";
import { Button } from "./ui/button";
import { useServerSandbox, localQuery } from "./ServerContext";
export default function ServersFleetView({ onSetup }) {
 const { server, dispatch } = useServerSandbox();
 const query = localQuery(server.servers);
  return <main className="min-h-full bg-[radial-gradient(circle_at_top_right,rgba(8,145,178,.13),transparent_35%),#05070a] px-4 py-10 text-slate-100 @min-[640px]:px-8"><div className="mx-auto max-w-5xl"><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-medium uppercase tracking-[.2em] text-cyan-400">Silence AI</p><h1 className="mt-2 text-3xl font-semibold">Servers</h1><p className="mt-2 text-slate-400">Add a server, install its native package, and follow provisioning to active protection.</p></div><div className="min-w-48"><Button variant="outline" onClick={() => onSetup(server.servers.find(row => !row.machineCredentialIssuedAt) || server.servers[0])}><Plus />Install / Setup</Button></div></div>{query.isLoading ? <p className="text-slate-400">Loading servers…</p> : query.error ? <Card className="border-rose-500/30 bg-rose-500/10"><CardContent>Servers are unavailable. {query.error.message}</CardContent></Card> : !query.data?.length ? <Card className="border-slate-800 bg-slate-900/60"><CardHeader><CardTitle>No servers added</CardTitle><CardDescription>Use Add Server above, then choose an Ubuntu DEB or Fedora RPM package manually.</CardDescription></CardHeader><CardContent className="flex items-center gap-2 text-sm text-cyan-300"><Plus className="size-4" />Package selection starts after the server is added.</CardContent></Card> : <div className="grid gap-4 @min-[768px]:grid-cols-2">{query.data.map((agent) => <Card key={agent.id} className="border-slate-800 bg-slate-900/60 transition hover:border-cyan-500/40"><CardHeader><div className="flex items-start justify-between"><span className="rounded-lg bg-cyan-500/10 p-2 text-cyan-300"><Server /></span><span className="inline-flex items-center gap-1 text-xs text-slate-400"><ShieldCheck className="size-4" />{agent.machineCredentialIssuedAt ? "Enrolled" : "Not enrolled"}</span></div><CardTitle className="mt-3">{agent.domain}</CardTitle><CardDescription>{agent.ipAddress || "IP address not reported"}</CardDescription></CardHeader><CardContent className="grid gap-2 @min-[640px]:grid-cols-2"><Button variant="outline" onClick={() => onSetup(agent)}><Download className="size-4" />{agent.machineCredentialIssuedAt ? "Setup / recovery" : "Install"}</Button><Button onClick={() => dispatch({ type: "SERVER_SELECT_AGENT", id: agent.id })}>Open Security <ArrowRight /></Button></CardContent></Card>)}</div>}</div></main>;
}
