export const competitiveComparisons = {
  web: {
    title: "AI-CSD Web vs. traditional alternatives",
    columns: [
      { label: "Feature" },
      { label: "AI-CSD Web", sublabel: "$350/mo annually" },
      { label: "Cloudflare Business", sublabel: "$200/mo annually" },
      { label: "AWS WAF", sublabel: "Usage based" },
      { label: "Check Point WAFaaS", sublabel: "Advanced / PAYG" },
    ],
    rows: [
      ["Full WAF protection", [true, true, true, true]],
      ["Dedicated Web IPS layer", [true, "Not a separate IPS", "Not a separate IPS", true]],
      ["Behavioral / AI-based web attack analysis", [true, "Managed / ML protections", "Managed rules & controls", true]],
      ["Behavioral CAPTCHA / bot challenge", [{ type: "check", comment: "Triggered when bot behavior is detected" }, { type: "check", comment: "Turnstile / Super Bot Fight Mode" }, { type: "check", comment: "CAPTCHA / Challenge" }, { type: "check", comment: "Bot protection" }]],
      ["Integrated Web Threat SIEM", [true, "Security analytics / logs", "CloudWatch / external tooling", "Security logs"]],
      ["AI security manager that can execute security actions", [{ type: "check", comment: "Can act on detected threats" }, false, false, "Automated protection"]],
      ["Automatic IP / subnet blocking", [true, "Via security rules", "Via WAF rules", true]],
      ["Country blocking", [{ type: "check", comment: "Built in" }, { type: "check", comment: "Via WAF rules" }, { type: "check", comment: "Geo match rules" }, true]],
      ["DDoS protection", [true, { type: "check", comment: "Unmetered DDoS protection" }, "Available via AWS WAF / Shield", true]],
      ["Blocked malicious requests billed as traffic", [{ type: "check", comment: "$0 — never billed" }, "Not request-metered like PAYG WAF", "Request-based billing", "All processed requests metered"]],
      ["Predictable integrated pricing", [{ type: "check", comment: "Platform + simple usage" }, "Plan + optional products", "ACL + rules + requests + add-ons", "Request based"]],
      ["Entry pricing / commercial model", [{ value: "$350/mo", comment: "billed annually" }, { value: "$200/mo", comment: "billed annually" }, "Usage based", { value: "$1,500", comment: "first 10M requests / PAYG" }]],
      ["Web security stack in one dashboard", [{ type: "check", comment: "WAF + IPS + CAPTCHA + SIEM + AI" }, "Multiple security capabilities", "Requires AWS services / integrations", "Integrated app security"]],
      ["Setup / management approach", [{ value: "≈ 5 min", comment: "Designed for no security expertise" }, "DNS + dashboard configuration", "AWS configuration", { value: "< 15 min", comment: "DNS-based deployment" }]],
    ],
  },
  email: {
    title: "AI-CSD Email vs. alternatives",
    columns: ["Feature", "AI-CSD Email", "Outlook / Gmail", "FortiMail"],
    rows: [
      ["View all emails across the domain from an Admin Console", [true, false, true]],
      ["Admin can delete employees' emails", [true, false, false]],
      ["Active protection against all types of email attacks", [true, false, true]],
      ["AI that manually checks the emails for phishing", [true, false, true]],
      ["AI forwards emails, sends them to specific folder, replies/makes response-draft to emails", [true, false, false]],
      ["Secure setup completion time", ["5 min", "5 min", "1–3 days"]],
    ],
  },
};
