// List of countries with their ISO codes, names, and flag URLs
export const countries = [
    { code: "AD", name: "Principality of Andorra" },
	{ code: "AE", name: "United Arab Emirates" },
	{ code: "AF", name: "Islamic Republic of Afghanistan" },
	{ code: "AG", name: "Antigua and Barbuda" },
	{ code: "AI", name: "Anguilla" },
	{ code: "AL", name: "Republic of Albania" },
	{ code: "AM", name: "Republic of Armenia" },
	{ code: "AO", name: "Republic of Angola" },
	{ code: "AQ", name: "Antarctica" },
	{ code: "AR", name: "Argentine Republic" },
	{ code: "AS", name: "American Samoa" },
	{ code: "AT", name: "Republic of Austria" },
	{ code: "AU", name: "Commonwealth of Australia" },
	{ code: "AW", name: "Aruba" },
	{ code: "AX", name: "Åland Islands" },
	{ code: "AZ", name: "Republic of Azerbaijan" },
	{ code: "BA", name: "Bosnia and Herzegovina" },
	{ code: "BB", name: "Barbados" },
	{ code: "BD", name: "People's Republic of Bangladesh" },
	{ code: "BE", name: "Kingdom of Belgium" },
	{ code: "BF", name: "Burkina Faso" },
	{ code: "BG", name: "Republic of Bulgaria" },
	{ code: "BH", name: "Kingdom of Bahrain" },
	{ code: "BI", name: "Republic of Burundi" },
	{ code: "BJ", name: "Republic of Benin" },
	{ code: "BL", name: "Saint Barthélemy" },
	{ code: "BM", name: "Bermuda" },
	{ code: "BN", name: "Brunei Darussalam" },
	{ code: "BO", name: "Plurinational State of Bolivia" },
	{ code: "BQ", name: "Bonaire, Sint Eustatius and Saba" },
	{ code: "BR", name: "Federative Republic of Brazil" },
	{ code: "BS", name: "Commonwealth of The Bahamas" },
	{ code: "BT", name: "Kingdom of Bhutan" },
	{ code: "BV", name: "Bouvet Island" },
	{ code: "BW", name: "Republic of Botswana" },
	{ code: "BY", name: "Republic of Belarus" },
	{ code: "BZ", name: "Belize" },
	{ code: "CA", name: "Canada" },
	{ code: "CC", name: "Cocos (Keeling) Islands" },
	{ code: "CD", name: "Democratic Republic of the Congo" },
	{ code: "CF", name: "Central African Republic" },
	{ code: "CG", name: "Republic of the Congo" },
	{ code: "CH", name: "Swiss Confederation" },
	{ code: "CI", name: "Republic of Côte d'Ivoire" },
	{ code: "CK", name: "Cook Islands" },
	{ code: "CL", name: "Republic of Chile" },
	{ code: "CM", name: "Republic of Cameroon" },
	{ code: "CN", name: "People's Republic of China" },
	{ code: "CO", name: "Republic of Colombia" },
	{ code: "CR", name: "Republic of Costa Rica" },
	{ code: "CU", name: "Republic of Cuba" },
	{ code: "CV", name: "Republic of Cabo Verde" },
	{ code: "CW", name: "Curaçao" },
	{ code: "CX", name: "Christmas Island" },
	{ code: "CY", name: "Republic of Cyprus" },
	{ code: "CZ", name: "Czech Republic" },
	{ code: "DE", name: "Federal Republic of Germany" },
	{ code: "DJ", name: "Republic of Djibouti" },
	{ code: "DK", name: "Kingdom of Denmark" },
	{ code: "DM", name: "Commonwealth of Dominica" },
	{ code: "DO", name: "Dominican Republic" },
	{ code: "DZ", name: "People's Democratic Republic of Algeria" },
	{ code: "EC", name: "Republic of Ecuador" },
	{ code: "EE", name: "Republic of Estonia" },
	{ code: "EG", name: "Arab Republic of Egypt" },
	{ code: "EH", name: "Western Sahara" },
	{ code: "ER", name: "State of Eritrea" },
	{ code: "ES", name: "Kingdom of Spain" },
	{ code: "ET", name: "Federal Democratic Republic of Ethiopia" },
	{ code: "FI", name: "Republic of Finland" },
	{ code: "FJ", name: "Republic of Fiji" },
	{ code: "FK", name: "Falkland Islands (Malvinas)" },
	{ code: "FM", name: "Federated States of Micronesia" },
	{ code: "FO", name: "Faroe Islands" },
	{ code: "FR", name: "French Republic" },
	{ code: "GA", name: "Gabonese Republic" },
	{ code: "GB", name: "United Kingdom of Great Britain and Northern Ireland" },
	{ code: "GD", name: "Grenada" },
	{ code: "GE", name: "Georgia" },
	{ code: "GF", name: "French Guiana" },
	{ code: "GG", name: "Bailiwick of Guernsey" },
	{ code: "GH", name: "Republic of Ghana" },
	{ code: "GI", name: "Gibraltar" },
	{ code: "GL", name: "Greenland" },
	{ code: "GM", name: "Republic of The Gambia" },
	{ code: "GN", name: "Republic of Guinea" },
	{ code: "GP", name: "Guadeloupe" },
	{ code: "GQ", name: "Republic of Equatorial Guinea" },
	{ code: "GR", name: "Hellenic Republic" },
	{ code: "GS", name: "South Georgia and the South Sandwich Islands" },
	{ code: "GT", name: "Republic of Guatemala" },
	{ code: "GU", name: "Guam" },
	{ code: "GW", name: "Republic of Guinea-Bissau" },
	{ code: "GY", name: "Co-operative Republic of Guyana" },
	{ code: "HK", name: "Hong Kong Special Administrative Region of China" },
	{ code: "HM", name: "Heard Island and McDonald Islands" },
	{ code: "HN", name: "Republic of Honduras" },
	{ code: "HR", name: "Republic of Croatia" },
	{ code: "HT", name: "Republic of Haiti" },
	{ code: "HU", name: "Hungary" },
	{ code: "ID", name: "Republic of Indonesia" },
	{ code: "IE", name: "Ireland" },
	{ code: "IL", name: "State of Israel" },
	{ code: "IM", name: "Isle of Man" },
	{ code: "IN", name: "Republic of India" },
	{ code: "IO", name: "British Indian Ocean Territory" },
	{ code: "IQ", name: "Republic of Iraq" },
	{ code: "IR", name: "Islamic Republic of Iran" },
	{ code: "IS", name: "Iceland" },
	{ code: "IT", name: "Italian Republic" },
	{ code: "JE", name: "Bailiwick of Jersey" },
	{ code: "JM", name: "Jamaica" },
	{ code: "JO", name: "Hashemite Kingdom of Jordan" },
	{ code: "JP", name: "Japan" },
	{ code: "KE", name: "Republic of Kenya" },
	{ code: "KG", name: "Kyrgyz Republic" },
	{ code: "KH", name: "Kingdom of Cambodia" },
	{ code: "KI", name: "Republic of Kiribati" },
	{ code: "KM", name: "Union of the Comoros" },
	{ code: "KN", name: "Federation of Saint Kitts and Nevis" },
	{ code: "KP", name: "Democratic People's Republic of Korea" },
	{ code: "KR", name: "Republic of Korea" },
	{ code: "KW", name: "State of Kuwait" },
	{ code: "KY", name: "Cayman Islands" },
	{ code: "KZ", name: "Republic of Kazakhstan" },
	{ code: "LA", name: "Lao People's Democratic Republic" },
	{ code: "LB", name: "Lebanese Republic" },
	{ code: "LC", name: "Saint Lucia" },
	{ code: "LI", name: "Principality of Liechtenstein" },
	{ code: "LK", name: "Democratic Socialist Republic of Sri Lanka" },
	{ code: "LR", name: "Republic of Liberia" },
	{ code: "LS", name: "Kingdom of Lesotho" },
	{ code: "LT", name: "Republic of Lithuania" },
	{ code: "LU", name: "Grand Duchy of Luxembourg" },
	{ code: "LV", name: "Republic of Latvia" },
	{ code: "LY", name: "State of Libya" },
	{ code: "MA", name: "Kingdom of Morocco" },
	{ code: "MC", name: "Principality of Monaco" },
	{ code: "MD", name: "Republic of Moldova" },
	{ code: "ME", name: "Montenegro" },
	{ code: "MF", name: "Saint Martin (French part)" },
	{ code: "MG", name: "Republic of Madagascar" },
	{ code: "MH", name: "Republic of the Marshall Islands" },
	{ code: "MK", name: "Republic of North Macedonia" },
	{ code: "ML", name: "Republic of Mali" },
	{ code: "MM", name: "Republic of the Union of Myanmar" },
	{ code: "MN", name: "Mongolia" },
	{ code: "MO", name: "Macao Special Administrative Region of China" },
	{ code: "MP", name: "Commonwealth of the Northern Mariana Islands" },
	{ code: "MQ", name: "Martinique" },
	{ code: "MR", name: "Islamic Republic of Mauritania" },
	{ code: "MS", name: "Montserrat" },
	{ code: "MT", name: "Republic of Malta" },
	{ code: "MU", name: "Republic of Mauritius" },
	{ code: "MV", name: "Republic of Maldives" },
	{ code: "MW", name: "Republic of Malawi" },
	{ code: "MX", name: "United Mexican States" },
	{ code: "MY", name: "Malaysia" },
	{ code: "MZ", name: "Republic of Mozambique" },
	{ code: "NA", name: "Republic of Namibia" },
	{ code: "NC", name: "New Caledonia" },
	{ code: "NE", name: "Republic of the Niger" },
	{ code: "NF", name: "Norfolk Island" },
	{ code: "NG", name: "Federal Republic of Nigeria" },
	{ code: "NI", name: "Republic of Nicaragua" },
	{ code: "NL", name: "Kingdom of the Netherlands" },
	{ code: "NO", name: "Kingdom of Norway" },
	{ code: "NP", name: "Federal Democratic Republic of Nepal" },
	{ code: "NR", name: "Republic of Nauru" },
	{ code: "NU", name: "Niue" },
	{ code: "NZ", name: "New Zealand" },
	{ code: "OM", name: "Sultanate of Oman" },
	{ code: "PA", name: "Republic of Panama" },
	{ code: "PE", name: "Republic of Peru" },
	{ code: "PF", name: "French Polynesia" },
	{ code: "PG", name: "Independent State of Papua New Guinea" },
	{ code: "PH", name: "Republic of the Philippines" },
	{ code: "PK", name: "Islamic Republic of Pakistan" },
	{ code: "PL", name: "Republic of Poland" },
	{ code: "PM", name: "Saint Pierre and Miquelon" },
	{ code: "PN", name: "Pitcairn" },
	{ code: "PR", name: "Commonwealth of Puerto Rico" },
	{ code: "PS", name: "State of Palestine" },
	{ code: "PT", name: "Portuguese Republic" },
	{ code: "PW", name: "Republic of Palau" },
	{ code: "PY", name: "Republic of Paraguay" },
	{ code: "QA", name: "State of Qatar" },
	{ code: "RE", name: "Réunion" },
	{ code: "RO", name: "Romania" },
	{ code: "RS", name: "Republic of Serbia" },
	{ code: "RU", name: "Russian Federation" },
	{ code: "RW", name: "Republic of Rwanda" },
	{ code: "SA", name: "Kingdom of Saudi Arabia" },
	{ code: "SB", name: "Solomon Islands" },
	{ code: "SC", name: "Republic of Seychelles" },
	{ code: "SD", name: "Republic of the Sudan" },
	{ code: "SE", name: "Kingdom of Sweden" },
	{ code: "SG", name: "Republic of Singapore" },
	{ code: "SH", name: "Saint Helena, Ascension and Tristan da Cunha" },
	{ code: "SI", name: "Republic of Slovenia" },
	{ code: "SJ", name: "Svalbard and Jan Mayen" },
	{ code: "SK", name: "Slovak Republic" },
	{ code: "SL", name: "Republic of Sierra Leone" },
	{ code: "SM", name: "Republic of San Marino" },
	{ code: "SN", name: "Republic of Senegal" },
	{ code: "SO", name: "Federal Republic of Somalia" },
	{ code: "SR", name: "Republic of Suriname" },
	{ code: "SS", name: "Republic of South Sudan" },
	{ code: "ST", name: "Democratic Republic of São Tomé and Príncipe" },
	{ code: "SV", name: "Republic of El Salvador" },
	{ code: "SX", name: "Sint Maarten (Dutch part)" },
	{ code: "SY", name: "Syrian Arab Republic" },
	{ code: "SZ", name: "Kingdom of Eswatini" },
	{ code: "TC", name: "Turks and Caicos Islands" },
	{ code: "TD", name: "Republic of Chad" },
	{ code: "TF", name: "French Southern Territories" },
	{ code: "TG", name: "Togolese Republic" },
	{ code: "TH", name: "Kingdom of Thailand" },
	{ code: "TJ", name: "Republic of Tajikistan" },
	{ code: "TK", name: "Tokelau" },
	{ code: "TL", name: "Democratic Republic of Timor-Leste" },
	{ code: "TM", name: "Turkmenistan" },
	{ code: "TN", name: "Republic of Tunisia" },
	{ code: "TO", name: "Kingdom of Tonga" },
	{ code: "TR", name: "Republic of Turkey" },
	{ code: "TT", name: "Republic of Trinidad and Tobago" },
	{ code: "TV", name: "Tuvalu" },
	{ code: "TW", name: "Taiwan, Province of China" },
	{ code: "TZ", name: "United Republic of Tanzania" },
	{ code: "UA", name: "Ukraine" },
	{ code: "UG", name: "Republic of Uganda" },
	{ code: "UM", name: "United States Minor Outlying Islands" },
	{ code: "US", name: "United States of America" },
	{ code: "UY", name: "Oriental Republic of Uruguay" },
	{ code: "UZ", name: "Republic of Uzbekistan" },
	{ code: "VA", name: "Vatican City State" },
	{ code: "VC", name: "Saint Vincent and the Grenadines" },
	{ code: "VE", name: "Bolivarian Republic of Venezuela" },
	{ code: "VG", name: "British Virgin Islands" },
	{ code: "VI", name: "United States Virgin Islands" },
	{ code: "VN", name: "Socialist Republic of Viet Nam" },
	{ code: "VU", name: "Republic of Vanuatu" },
	{ code: "WF", name: "Wallis and Futuna" },
	{ code: "WS", name: "Independent State of Samoa" },
	{ code: "YE", name: "Republic of Yemen" },
	{ code: "YT", name: "Mayotte" },
	{ code: "ZA", name: "Republic of South Africa" },
	{ code: "ZM", name: "Republic of Zambia" },
	{ code: "ZW", name: "Republic of Zimbabwe" },
];

// Function to get country name by code
export const getCountryName = (code) => {
  const country = countries.find(c => c.code === code);
  return country ? country.name : code;
};

// Function to get country code by name
export const getCountryCode = (name) => {
  const country = countries.find(c => c.name === name);
  return country ? country.code : null;
};
