"use client";

import React, { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Bot, Database, ShieldCheck, Workflow, Wrench } from "lucide-react";

export const McpFlowAnimation = () => {
  const [activeSegment, setActiveSegment] = useState(0);
  const totalSegments = 3; // 4 steps means 3 connecting segments
  const cycleDuration = 2000; // 2 seconds per segment

  useEffect(() => {
    const interval = setInterval(() => {
      setActiveSegment((prev) => (prev + 1) % totalSegments);
    }, cycleDuration);
    return () => clearInterval(interval);
  }, []);

  const steps = [
    {
      id: "llm-start",
      label: "Your LLM",
      subLabel: "Invokes MCP Tool",
      Icon: Bot,
      color: "text-blue-400",
      bg: "bg-blue-500/10",
      border: "border-blue-500/20",
    },
    {
      id: "mcp",
      label: "Supreme 2 MAX",
      subLabel: "Scans Entire Repo",
      Icon: Workflow,
      SubIcon: ShieldCheck,
      color: "text-fuchsia-400",
      bg: "bg-fuchsia-500/10",
      border: "border-fuchsia-500/30",
      glow: true,
    },
    {
      id: "report",
      label: "Analysis Report",
      subLabel: "Generated by MCP",
      Icon: Database,
      color: "text-emerald-400",
      bg: "bg-emerald-500/10",
      border: "border-emerald-500/20",
    },
    {
      id: "fix",
      label: "LLM Fixes Code",
      subLabel: "Using Report",
      Icon: Wrench,
      color: "text-blue-400",
      bg: "bg-blue-500/10",
      border: "border-blue-500/20",
    },
  ];

  return (
    <div className="w-full py-10 relative">
        {/* Continuous background line */}
        <div className="absolute inset-0 flex items-center justify-center pointer-events-none">
            {/* Desktop Line */}
            <div className="hidden md:block w-3/4 h-0.5 bg-slate-800/50" />
            {/* Mobile Line */}
            <div className="md:hidden w-0.5 h-3/4 bg-slate-800/50" />
        </div>

      <div className="flex flex-col gap-8 md:flex-row md:items-center md:justify-center relative z-10">
        {steps.map((step, index) => {
          const Icon = step.Icon;
          const SubIcon = step.SubIcon;
          const isLast = index === steps.length - 1;

          return (
            <React.Fragment key={step.id}>
              {/* Step Node */}
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: index * 0.2, duration: 0.5 }}
                className={`relative z-10 flex flex-col items-center justify-center rounded-xl border ${step.border} ${step.bg} p-6 backdrop-blur-sm w-full md:w-64`}
              >
                {/* Glow Effect for the main node */}
                {step.glow && (
                  <motion.div
                    className="absolute inset-0 -z-10 bg-fuchsia-500/20 blur-xl"
                    animate={{ opacity: [0.5, 0.8, 0.5] }}
                    transition={{ duration: 3, repeat: Infinity }}
                  />
                )}

                <div className="mb-4 flex items-center justify-center gap-2">
                  <Icon className={`h-8 w-8 ${step.color}`} />
                  {SubIcon && <SubIcon className={`h-6 w-6 ${step.color}`} />}
                </div>
                
                <h3 className={`text-center font-semibold ${step.color}`}>{step.label}</h3>
                <div className="mt-1 text-xs text-slate-400 text-center uppercase tracking-wider">
                  {step.subLabel}
                </div>
                
                {step.glow && (
                  <div className="mt-2 text-xs text-fuchsia-200/50 text-center font-mono bg-fuchsia-500/10 px-2 py-1 rounded">
                    Full Context
                  </div>
                )}
              </motion.div>

              {/* Connecting Arrow (Desktop) */}
              {!isLast && (
                <div className="hidden flex-1 items-center justify-center px-2 md:flex min-w-[40px]">
                  <div className="relative h-0.5 w-full bg-slate-700">
                    <AnimatePresence>
                        {activeSegment === index && (
                        <motion.div
                            className="absolute top-1/2 -mt-1 h-2 w-2 rounded-full bg-white shadow-[0_0_10px_rgba(255,255,255,0.8)]"
                            initial={{ left: "0%", opacity: 0 }}
                            animate={{ left: "100%", opacity: 1 }}
                            exit={{ opacity: 0 }}
                            transition={{
                              duration: 2, /* Matches cycleDuration */
                              ease: "linear"
                            }}
                        />
                        )}
                    </AnimatePresence>
                    <div className="absolute -right-1 top-1/2 -mt-[5px] h-0 w-0 border-b-[5px] border-l-[8px] border-t-[5px] border-b-transparent border-l-slate-700 border-t-transparent" />
                  </div>
                </div>
              )}

              {/* Connecting Arrow (Mobile) */}
              {!isLast && (
                <div className="flex h-10 items-center justify-center md:hidden">
                  <div className="h-full w-0.5 bg-slate-700 relative">
                    <AnimatePresence>
                      {activeSegment === index && (
                        <motion.div
                            className="absolute left-1/2 -ml-1 w-2 h-2 rounded-full bg-white shadow-[0_0_10px_rgba(255,255,255,0.8)]"
                            initial={{ top: "0%", opacity: 0 }}
                            animate={{ top: "100%", opacity: 1 }}
                            exit={{ opacity: 0 }}
                            transition={{
                                duration: 2, /* Matches cycleDuration */
                                ease: "linear"
                            }}
                        />
                      )}
                    </AnimatePresence>
                    
                    <div className="absolute -bottom-1 left-1/2 -ml-[5px] h-0 w-0 border-l-[5px] border-t-[8px] border-r-[5px] border-l-transparent border-t-slate-700 border-r-transparent" />
                  </div>
                </div>
              )}
            </React.Fragment>
          );
        })}
      </div>
    </div>
  );
};

export default McpFlowAnimation;
